Document: libcamera-apps
Title: Debian libcamera-apps Manual
Author: <insert document author here>
Abstract: This manual describes what libcamera-apps is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libcamera-apps/libcamera-apps.sgml.gz

Format: postscript
Files: /usr/share/doc/libcamera-apps/libcamera-apps.ps.gz

Format: text
Files: /usr/share/doc/libcamera-apps/libcamera-apps.text.gz

Format: HTML
Index: /usr/share/doc/libcamera-apps/html/index.html
Files: /usr/share/doc/libcamera-apps/html/*.html
